### ISSUE TITLE
1.20.x support

### ISSUE THREAD

**Issue by cyyynthia** [kawaiicakes/IceBoatNerfReforged#1]
Hi, I've been looking for a mod that does this for a bit and I came across the Fabric version, and then your Forge port. Would it be possible to update this mod to support Minecraft 1.20.x?

I'm really looking for a mod to disable this :sob:

**Comment by kawaiicakes** [comment]
> Hi, I've been looking for a mod that does this for a bit and I came across the Fabric version, and then your Forge port. Would it be possible to update this mod to support Minecraft 1.20.x?
> 
> I'm really looking for a mod to disable this 😭

Bonjour,

Pas d'problème. I will start working on it and can get a release out shortly. Please let me know here if for some reason it doesn't work.

**Comment by cyyynthia** [comment]
Woah, merci for the insanely fast reply ❤️

~~Fellow frenchie, or someone who tortured herself to learn french?~~ 👀

**Comment by kawaiicakes** [comment]
> Woah, merci for the insanely fast reply ❤️
> 
> ~Fellow frenchie, or someone who tortured herself to learn french?~ 👀

I am a Canadian who did the latter lol. Anyhow, the file has been submitted to Curseforge and is pending malware review. Kindly inform me if the mod works or not here when you get a chance to try it. The (already non-existent) code is unchanged, but the specific class and method being targeted is consistent across the versions I've uploaded v1.1.0 for. Theoretically it should work.

**Comment by cyyynthia** [comment]
I gave it a test, seems like Forge doesn't want to load the mod:

```
[20:57:46] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'minecraft', Requested by: 'iceboatnerf', Expected range: '[1.17.1,1.20,]', Actual version: '1.20.1'
```

**Comment by kawaiicakes** [comment]
> I gave it a test, seems like Forge doesn't want to load the mod:
> 
> ```
> [20:57:46] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
> 	Mod ID: 'minecraft', Requested by: 'iceboatnerf', Expected range: '[1.17.1,1.20,]', Actual version: '1.20.1'
> ```

Submitted a new file. Currently under review. I messed the Maven versioning up.

**Comment by cyyynthia** [comment]
It works! Huge thanks for the speedy update!! ❤️
